import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface-tint': '#006e2d',
        'surface-container-highest': '#d3e4fe',
        outline: '#6e7b6c',
        'on-secondary-container': '#626567',
        'surface-container-high': '#dce9ff',
        'on-tertiary': '#ffffff',
        'surface-container-low': '#eff4ff',
        'on-secondary-fixed-variant': '#444749',
        'tertiary-container': '#667781',
        'on-error-container': '#93000a',
        'on-background': '#0b1c30',
        'on-tertiary-fixed-variant': '#384953',
        tertiary: '#4e5e68',
        'on-primary-fixed': '#002109',
        error: '#ba1a1a',
        'on-secondary-fixed': '#191c1e',
        'primary-container': '#00873a',
        'on-primary-fixed-variant': '#005320',
        'tertiary-fixed-dim': '#b7c9d5',
        'tertiary-fixed': '#d3e5f1',
        'on-primary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#213145',
        'surface-container': '#e5eeff',
        'secondary-fixed-dim': '#c4c7c9',
        secondary: '#5c5f61',
        'surface-variant': '#d3e4fe',
        'primary-fixed': '#7ffc97',
        'surface-dim': '#cbdbf5',
        'outline-variant': '#bdcaba',
        'on-secondary': '#ffffff',
        'secondary-container': '#e0e3e5',
        'on-tertiary-container': '#fbfcff',
        'on-error': '#ffffff',
        'primary-fixed-dim': '#62df7d',
        'secondary-fixed': '#e0e3e5',
        'on-surface': '#0b1c30',
        primary: '#006b2c',
        'inverse-primary': '#62df7d',
        surface: '#f8f9ff',
        'on-primary-container': '#f7fff2',
        background: '#f8f9ff',
        'on-tertiary-fixed': '#0c1e26',
        'on-surface-variant': '#3e4a3d',
        'error-container': '#ffdad6',
        'inverse-on-surface': '#eaf1ff',
        'surface-bright': '#f8f9ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '32px',
        gutter: '24px',
        unit: '4px',
        'margin-mobile': '16px',
        'container-max': '1280px',
      },
      fontFamily: {
        'label-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'display-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'title-md': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'title-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
} satisfies Config
